### ISSUE TITLE
Help getting this to work please

### ISSUE THREAD

**Issue by drtinaz** [ThisSmartHouse/hass-arvee#7]
I'm not sure if I missed a step or what. Please excuse my ignorance. I installed via HACS, restarted HA, and then proceeded to setup the automation. Your description says that this works the same as the update location service, which I have working with no issues. I duplicated the set location automation and changed the service to set_geo_timezone and save the automation and get this error: Error in describing action: Cannot read properties of undefined (reading 'set_geo_timezone')

If i goto settings/devices and services/add integration and click on arvee then I get: This integration cannot be added from the UI
You can add this integration by adding it to your 'configuration.yaml'. See the documentation for more information

I have looked over the documentation but I can't find the answer. What am I doing wrong?

**Comment by drtinaz** [comment]
Here is my automation

```
alias: Set Timezone
description: Updates Home Assistant Timezone From GPS
triggers:
  - trigger: state
    entity_id:
      - sensor.cerbo_gx_gps_latitude
      - sensor.cerbo_gx_gps_longitude
    for:
      hours: 0
      minutes: 5
      seconds: 0
conditions: []
actions:
  - metadata: {}
    data:
      latitude: |
        {{ states("sensor.cerbo_gx_gps_latitude") }}
      longitude: |
        {{ states("sensor.cerbo_gx_gps_longitude") }}
    action: arvee.set_geo_timezone
mode: single
max_exceeded: silent
```
